spring.application.name=employee-service-app

spring.config.import=optional:configserver:http://localhost:8888


management.tracing.sampling.probability=1.0

logging.pattern.level=%5p [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%X{traceId:-},%X{spanId:-}] %c - %m%n

logging.level.org.springframework.web=DEBUG

management.zipkin.endpoint=http://localhost:9411/api/v2/spans



# ===== CIRCUIT BREAKER CONFIG =====

#how many recent calls to monitor
resilience4j.circuitbreaker.instances.deptServiceCB.sliding-window-size=4

# if 50% of those 10 calls fail ? trip to OPEN
resilience4j.circuitbreaker.instances.deptServiceCB.failure-rate-threshold=50

# stay OPEN for 10 seconds before trying HALF-OPEN
resilience4j.circuitbreaker.instances.deptServiceCB.wait-duration-in-open-state=10s

# in HALF-OPEN, allow only 3 test calls
resilience4j.circuitbreaker.instances.deptServiceCB.permitted-calls-in-half-open-state=3

# show circuit breaker state in /actuator/health
resilience4j.circuitbreaker.instances.deptServiceCB.register-health-indicator=true

# ===== ACTUATOR CONFIG =====

# enable circuit breaker info in health endpoint
management.health.circuitbreakers.enabled=true

# expose all actuator endpoints (health, info, metrics etc)
management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always