spring.application.name=api-gateway

server.port=9191

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Routes for Department MicroService
spring.cloud.gateway.routes[0].id=department-service
spring.cloud.gateway.routes[0].uri=lb://department-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/deptapp/**

#Routes for Employee MicroService
spring.cloud.gateway.routes[1].id=employee-service-app
spring.cloud.gateway.routes[1].uri=lb://employee-service-app
spring.cloud.gateway.routes[1].predicates[0]=Path=/empapp/**